chunking_strategies:
  - name: simple_chunk_100_overlap_10
    method: simple_split
    params:
      chunk_size: 100
      chunk_overlap: 10
  - name: simple_chunk_1
    method: simple_split
    params:
      chunk_size: 1000
      chunk_overlap: 200
  - name: recursive_char_split_1
    method: recursive_character_text_splitter
    params:
      chunk_size: 150
      chunk_overlap: 15
      separators: ["\n\n", "\n", " ", ""]
  - name: embedding_chunk
    method: outside # special method, load chunking results directly
    source_type: libsql
    source_path: "data/load_chunks/JsBWMUpm3M4wx1qwCMuA5"